name: Build bot

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: wstunnel-builder-cache
        id: docker_build_wstunnel-cache
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/erebe/wstunnel:builder-cache
          target: builder-cache
      - name: wstunnel
        id: docker_build_wstunnel
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/terranblake/wstunnel:latest
      - name: wstunnel Image digest
        run: echo wstunnel ${{ steps.docker_build_wstunnel.outputs.digest }}
      - name: Trigger deployer
        run: |
          payload='{ "application_name": "wstunnel", "image_digest": "${{ steps.docker_build_wstunnel.outputs.digest }}", "image_tag": "latest" }'
          token='X-Webhook-Token: ${{ secrets.WEBHOOK_SECRET }}'
          curl -i -X POST -H 'Content-Type: application/json' -H "${token}"  -d "${payload}" https://hooks.terranblake.com/hooks/deploy
          
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
#    - name: Install stack
#      run: |
#        curl -sSL https://get.haskellstack.org/ | sh
        
    - name: Setup GHC
      run: |
        stack setup
        
    - name: Build
      run: |
        stack install
        
    - uses: actions/upload-artifact@v1
      with:
        name: wstunnel-windows-x64.exe
        path: C:\Users\runneradmin\AppData\Roaming\local\bin\wstunnel.exe
      
      
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      
#    - name: Install stack
#      run: |
#        curl -sSL https://get.haskellstack.org/ | sh
        
    - name: Setup GHC
      run: |
        stack setup
        
    - name: Build
      run: |
        stack install
        
    - uses: actions/upload-artifact@v1
      with:
        name: wstunnel-macos
        path: /Users/runner/.local/bin/wstunnel
